marxin/cvise

clang_delta/CMakeLists.txt

It is not always the case that there exits a unified libLLVM-file, if you build
clang yourself it may be split into multiple libraries. Thus it is better to
import the clang dependencies using the names exported from ClangConfig.cmake
than refering to the archive file names explicitly.

Switch to lib names exported from ClangConfig.cmake

---

cvise/utils/testing.py

When creating a back-up file, `cvise` creates the back-up file called:
```
orig_file = "{}.orig".format(os.path.splitext(f)[0])
```
while `creduce` would do this:
```
orig_file = "{}.orig".format(f)
```
This PR ensures that `cvise` creates back-up files in the same location as `creduce` would.
Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

When backing-up original file, do not strip original file extension (`creduce` compatibility)

---

INSTALL.md

Debian packages these, so they can be added to the recommended
dependency install script.
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

INSTALL: add delta and unifdef debian packages

---

clang_delta/CommonRenameClassRewriteVisitor.h
clang_delta/RemoveNamespace.cpp
clang_delta/RewriteUtils.cpp
clang_delta/Transformation.cpp
clang_delta/TransformationManager.cpp

It seems StringRef is no longer convertible to std::string, and
clang::FileManager moved since llvm-9.
Note: ToT LLVM is currently post-llvm-10 (i.e. llvm-11).
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

clang_delta: fix build for ToT LLVM

---

CMakeLists.txt
clang_delta/CMakeLists.txt
clex/CMakeLists.txt
cvise.py
cvise/CMakeLists.txt

Use GNUInstallDirs to make install locations configurable rather than
hardcoding 'bin' and 'share'.  This also means allowing any relative
path between the script and share directory rather than '../share'.

Use GNUInstallDirs for configurable install locations

---

CMakeLists.txt

pebble is required only at runtime, it should not prevent the package
from being built.

cmake: Do not fail on missing pebble

---

build_and_test.sh
cvise/passes/ifs.py
cvise/tests/test_ifs.py

Before the change IfPass was looping on the same fine:
```
$ cvise --timestamp --remove-pass IncludesPass,UnIfDefPass,CommentsPass \
--print-diff --debug ./test_cvise.bash *.h *.cpp
2020-08-09 11:45:38,176 DEBUG granularity reduced to 2
2020-08-09 11:45:38,211 DEBUG granularity reduced to 2
2020-08-09 11:45:41,990 DEBUG granularity reduced to 2
2020-08-09 11:45:42,211 DEBUG granularity reduced to 2
2020-08-09 11:45:46,045 DEBUG granularity reduced to 2
...
```
This happens because due to two problems:
1. `state.advance()` is not a mutating operation in `ifs.py`.
As a result increment was lost.
2. `IfPass` iteration was not able to make progress for either
`#if 0` or `#if 1` cases.
This change fixes [1.].

passes/ifs.py: fix infinite loop in IfPass

---

INSTALL.md
clex/CMakeLists.txt
clex/driver.c
delta/CMakeLists.txt

Even with the information in #17, building cvise on windows was quite difficult for me as I am unfamiliar with cmake.
This pull request documents the steps I used and fixes some build errors.

Allow and document building on windows

---

README.md

Compilations with lots of errors are slow, and are ultimately discarded,
so better to fail quickly.

README: add a tip about -Wfatal-errors

---

clang_delta/ExpressionDetector.cpp
clang_delta/TransformationManager.cpp

* replaces `Invocation.setLangDefaults` with
`LangOptions::setLangDefaults`
* Fixes virtual interface
Fixes #74
Co-authored-by: Martin Liska <mliska@suse.cz>

refactors so that the project is LLVM 15-compatible

---

clang_delta/CMakeLists.txt
clang_delta/ClassTemplateToClass.cpp
clang_delta/tests/class-template-to-class/test1.cc
clang_delta/tests/class-template-to-class/test1.output
clang_delta/tests/test_clang_delta.py

The class-template-to-class transformation did not remove the template keyword from out-of-line methods.
```
template <class> class j {
public:
void func();
template <class c>
void func2(c p);
};
template <class m> void j<m>::func() {
return *this;
}
```
was translated to
```
class j {
public:
void func();
template <class c>
void func2(c p);
};
template <class m> void j::func() {
return *this;
}
```
the template specifier of `j::func` was not removed.

class-template-to-class transformation was not working with out-of-line method definitions

---

clang_delta/CMakeLists.txt
clang_delta/MemberToGlobal.cpp
clang_delta/MemberToGlobal.h
clang_delta/tests/member-to-global/test1.cc
clang_delta/tests/member-to-global/test1.output
clang_delta/tests/member-to-global/test2.cc
clang_delta/tests/member-to-global/test2.output
clang_delta/tests/member-to-global/test3.cc
clang_delta/tests/member-to-global/test3.output
clang_delta/tests/member-to-global/test4.cc
clang_delta/tests/member-to-global/test4.output
clang_delta/tests/member-to-global/test5.cc
clang_delta/tests/member-to-global/test5.output
clang_delta/tests/member-to-global/test6.cc
clang_delta/tests/member-to-global/test6.output
clang_delta/tests/test_clang_delta.py
cvise/pass_groups/all.json

Added member-to-global pass that tries to move declaration within a record in front of the record.
A supports and was tested with typedefs/using, static/non-static functions, static/non-static variables.

Added member-to-global pass that moves declarations within a record (class or struct) in front of the record

---

clang_delta/CMakeLists.txt
clang_delta/RenameOperator.cpp
clang_delta/RenameOperator.h
clang_delta/tests/rename-operator/test1.cc
clang_delta/tests/rename-operator/test1.output
clang_delta/tests/rename-operator/test2.cc
clang_delta/tests/rename-operator/test2.output
clang_delta/tests/test_clang_delta.py
cvise/pass_groups/all.json

A pass to rename operator functions (e.g. operator +) to regular function names op1, op2, ...
Relevant operators are replaced by function calls, e.g. a + b => a.op1(b).
The pass renames all functions with --count=1 and single functions with >= 2.

Added rename-operator pass that converts operator functions (e.g. operator +) to regular functions

---

clang_delta/CMakeLists.txt

Improve compilation on MSVC
/bigobj is required for me
/mp enables parallel build ... otherwise build is REALLY slow
Deactivated warnings are copied from LLVM project

CMake: Fixed compilation, enabled parallel builds and deactivated unnecessary warnings for MSVC

---

clang_delta/CMakeLists.txt
clang_delta/InstantiateTemplateParam.cpp
clang_delta/tests/instantiate-template-param/test6.cc
clang_delta/tests/instantiate-template-param/test6.output
clang_delta/tests/test_clang_delta.py

This my first of a series of PR for improving the instantiate-template-param pass.
It fixes a bug that always the type of the first parameter was used for replacement. In the example g was replaced by int instead of double.

Bugfix: instantiate-template-param transformation used always the type of the first template parameter

---

clang_delta/ReduceClassTemplateParameter.cpp

Unfortunately, I do not have a test case. My smallest one is 3000 bytes because cvise cannot reduce it further :( I think we need some kind of template reordering pass...

Fixed crash in reduce-class-template-param

---

clang_delta/CMakeLists.txt
clang_delta/MergeBaseClass.cpp
clang_delta/MoveFunctionBody.cpp
clang_delta/RemoveBaseClass.cpp
clang_delta/RemoveBaseClass.h
clang_delta/RewriteUtils.cpp
clang_delta/RewriteUtils.h
clang_delta/TransformationManager.h
clang_delta/tests/merge-base-class/test1.cc
clang_delta/tests/merge-base-class/test1.output
clang_delta/tests/merge-base-class/test2.cc
clang_delta/tests/merge-base-class/test2.output
clang_delta/tests/merge-base-class/test3.cc
clang_delta/tests/merge-base-class/test3.output
clang_delta/tests/remove-base-class/test1.cc
clang_delta/tests/remove-base-class/test1.output
clang_delta/tests/remove-base-class/test2.cc
clang_delta/tests/remove-base-class/test2.output
clang_delta/tests/remove-base-class/test3.cc
clang_delta/tests/remove-base-class/test3.output
clang_delta/tests/remove-base-class/test4.cc
clang_delta/tests/remove-base-class/test4.output
clang_delta/tests/test_clang_delta.py
cvise/pass_groups/all.json

1. The transformation learned to merge templated base classes
2. The transformation was splitted into two transformation: (1) remove-base-class only removes the base class, (2) merge-base-class removes the base class and copies the content of the base class

Improved merge-base-class transformation

---

cvise.py

My system (`NixOS`) has one well-defined shell: `/bin/sh`.
But normally programs use either `/run/current-system/sw/bin/bash` or the `bash` from `PATH`. They use `/usr/bin/env` for that.
The change calls shell via `/usr/bin/env` to use `PATH` lookup.

cvise.py: call shell vial `/usr/bin/env` indirection instead of `/bin`

---

clang_delta/ClangDelta.cpp
clang_delta/tests/test_clang_delta.py

This adds the version of clang currently in use to the output from clang_delta --version and changes the test script to use this information instead of looking at the list of dynamic libraries when checking which clang version is in use. This allows the tests to run when clang_delta is statically linked against libClang.

Add clang version string to clang_delta --version

---

CMakeLists.txt
clex/CMakeLists.txt
delta/CMakeLists.txt

- Check whether `CMAKE_CXX_COMPILER_ID` contains the string `Clang` rather than being exactly equal.  This way it also matches `AppleClang`, which is what CMake uses for the default compiler on macOS; see also:
https://cmake.org/cmake/help/latest/policy/CMP0025.html
- Add `-Wno-sign-compare` to the special options for Flex-generated .c files, because Apple's Flex generates code that produces this warning by default.  Compare to e.g.:
https://github.com/vlm/asn1c/issues/321

CMakeLists changes to fix macOS build:

---

cvise.py

I followed the discussion in this(https://github.com/marxin/cvise/pull/129) thread and decided to send a PR.
With these changes, logs are both displayed on stdout and stored in the logfile when the `--log-file` parameter is provided.
Would it be more appropriate to solely store them in a file without displaying them on stdout if the parameter is provided?

Removed basicConfig & fixed working of --log-file arg

---

cvise/utils/error.py
cvise/utils/testing.py

Make CVise understand files in a filesystem tree

---

cvise.py
cvise/cvise.py
cvise/utils/testing.py

Sometimes it's enough to reduce a testcase by, say, 95%.  This commit lets the user specify this threshold and CVise doesn't need to spend time trying to make progress until it can no longer do so.
For example:
`cvise <args> --stopping-threshold 0.95 ./interesting.sh test_case`
This can speed up CVise in some cases.
Constructive feedback is very welcome.

Implement a stopping threshold

---

INSTALL.md

Otherwise cvise will fail to run when first started.

Also instruct to install chardet on Windows

---

CMakeLists.txt
clang_delta/CMakeLists.txt

Without this, it's compiled with C++14, which makes the build fail, because `std:optional` is not supported under C++14.

Ensure that clang delta is also compiled with C++17 on Windows

---

clang_delta/CommonRenameClassRewriteVisitor.h
clang_delta/RemoveNamespace.cpp

Remove uses of ClassTemplateSpecializationDecl::getTypeAsWritten

---

cvise/utils/testing.py

Catch timeout from Pebble for Python 3.10 and older

---

cvise/utils/testing.py

The exitcode isn't guaranteed to be set whenever |result| is |OK|, because the code that sets it (the caller of run_test()) might be skipped on exception.
The code after the assert seems to correctly handle the case when |exitcode| is |None|, so this commit just deletes the assert. This fixes #157.

Delete assert of exitcode in TestManager

---

cvise/utils/misc.py

Close the file handle after it's not needed anymore.
This problem was detected by pytest in my work for #156:
```
cvise/utils/misc.py:8: ResourceWarning: unclosed file
<_io.TextIOWrapper name='input.txt' mode='r' encoding='UTF-8'>
open(filename).read()
```

Fix unclosed file in is_readable_file

---

cvise/CMakeLists.txt
cvise/tests/test_test_manager.py
cvise/utils/testing.py

Implement unit tests specifically for the TestManager class, with stubbing out the pass logic. Cover the basic successful minimization scenarios and basic error scenarios.
This lays groundwork for the regression testing of #156.

Add basic tests for TestManager

---

cvise/tests/test_test_manager.py
cvise/utils/testing.py

Make sure that we don't proceed when a buggy pass returns an
unmodified file - for this, consistently validate the pass' results on
both codepaths (in process_done_futures() and wait_for_first_success()).
Besides fixing the hang that was possible when a pass misbehaved,
there are a couple of other side effects:
* more cases of ERRORs in a pass will be reported - previously only
the ones on the first codepath were handled;
* max_improvement is enforced stricter now - previously the second
codepath allowed a larger reduction to sneak in.
This fixes https://github.com/marxin/cvise/issues/156.

Fix hang when buggy (unaltered) OK comes after STOP

---

cvise/passes/lines.py
cvise/tests/test_lines.py
tests/test_cvise.py

This reduces the overhead slightly and prevents the files from
growing noticeably when the lines passes start. This fixes #163.
Note that this new logic has a safeguard that falls back to the
previous behavior (which takes the topformflat's output as-is) in
case the interestingness script starts failing.

Trim leading/trailing spaces after topformflat

---

cvise/passes/balanced.py
cvise/passes/blank.py
cvise/passes/clang.py
cvise/passes/clangbinarysearch.py
cvise/passes/clex.py
cvise/passes/comments.py
cvise/passes/gcdabinary.py
cvise/passes/ifs.py
cvise/passes/includeincludes.py
cvise/passes/includes.py
cvise/passes/indent.py
cvise/passes/ints.py
cvise/passes/line_markers.py
cvise/passes/lines.py
cvise/passes/peep.py
cvise/passes/special.py
cvise/passes/ternary.py
cvise/passes/unifdef.py
cvise/tests/test_test_manager.py
cvise/utils/testing.py

Change all subclasses to use **kwargs instead of mentioning the unused parameter (using the real name or using "_").
This refactoring allows us to easily add/remove parameters needed for specific subclasses without having to change unrelated classes. This is preparation work for adding new logic for #169.

Refactor arg passing for Pass.new()

---

.github/workflows/build-llvm-nightly.yml
clang_delta/CommonRenameClassRewriteVisitor.h
clang_delta/RemoveNamespace.cpp
clang_delta/RemoveUnusedFunction.cpp
clang_delta/RenameFun.cpp
clang_delta/Transformation.cpp
clang_delta/TransformationManager.cpp

Adjust the C++ code according to backwards-incompatible changes
that are being made in the tip-of-the-tree LLVM sources (for the upcoming
21 release).
Switch the CI-LLVM-nightly job to using LLVM version 21.
This fixes #171.

Add support for LLVM 21 as of 2025.06.24

---

cvise/passes/line_markers.py
cvise/tests/test_line_markers.py

Reimplement the line_markers pass using the hints architecture -
this acts as the simple first example of a heuristic implemented that
way. This migration is intended to have no functional changes.
This is part of the effort tracked by #169.

hints: Migrate line_markers pass

---

cvise/tests/test_lines.py
delta/topformflat.l

Stop producing hints for deleting code at levels smaller than the specified
depth (threshold). This should significantly improve the success rate for
all depths greater than zero, because we'll stop trying partially removing
outer constructs.
For example, for a top-level C function, running Lines with arg=1 should
only attempt removing statements inside the function body, but don't
try deleting the function signature alone or deleting the closing curly
brace alone.
Note: the downside of this change is that when running Lines for arg>1,
the heuristic will stop trying to delete higher-level chunks of code. We
consider this not to be a problem because one of planned follow-up
changes will run all Lines passes concurrently, in an interleaving fashion.

Improve Lines: only remove exactly at given depth

---

cvise/utils/testing.py

Store all per-job information in a separate Job object instead of using several independent dicts. Also explicitly store the Pass in the Job, instead of assuming all active jobs have the same pass.
This is preparation for the introduction of interleaved (concurrent) execution of different passes. The current PR is intended to have no functional changes.

Refactor job management in TestManager

---

cvise/tests/test_hint.py
cvise/utils/hint.py

For now, this is only intended to be used in tests of tools that'll emit hints as JSONL - so that we can test the produced hints without needlessly compressing them.

hints: Support loading uncompressed hint files

---

cvise/cvise.py
cvise/tests/test_test_manager.py
cvise/utils/statistics.py
cvise/utils/testing.py

Add basic support of executing different passes in an interleaving fashion to TestManager.
This paves the way for improving performance, both worst-case (to avoid C-Vise being
stuck on a badly performing heuristic meanwhile others would reduce the file quicker)
as well as average-case (once we implement folding of concurrently-discovered
reductions). We only plan to enable the interleaving mode for hint-based passes,
because they are designed to leave inputs unmodified and to have easily mergeable
reductions.
This commit doesn't wire up new logic to the CLI; only tests exercise this mode at the moment.

interleaving: Manager can run different passes simultaneously

---

cvise-cli.py
cvise/passes/hint_based.py
cvise/tests/test_hint.py
cvise/utils/hint.py
tests/test_cvise.py

Add command-line options to C-Vise to apply the given set of hints to the test case.
This is currently intended to be used in clang_delta unit tests (which, despite being written in Python, are not part of the C-Vise module and hence cannot import hints.py directly). Additionally, this might be useful in the long run for developers working on new passes for C-Vise.

hints: Add CLI for applying hints to input

---

cvise/cvise.py

There was a bug that the threshold check kept repeatedly using the same file size - the one before the loop over passes started.
This is probably a rarely used feature, but uploading this as a separate fix to make follow-up refactoring of the same code easier to review.

Fix --stopping-threshold checked too rarely

---

cvise/cvise.py

This makes the difference between pass categories ("first"/"main"/"last") hardcoded in a more declarative way in the code, and unifies the logic of how their passes are executed.
It's intended to be a pure refactoring change. It's a preparation for the introduction of "interleaving" pass categories, for which we want to reuse most of the existing logic.

Refactor pass category logic of pass group config

---

cvise/cvise.py
cvise/passes/abstract.py
cvise/utils/testing.py

Since the migration of the Lines pass to hints, none of heuristics modifies the input file during initialization. This means the "check_sanity" logic (double-checking whether the modified input still satisfies the interestingness script) isn't needed anymore as a pass parameter.

Stop using check_sanity for passes

---

cvise/cvise.py
cvise/passes/abstract.py
cvise/tests/test_test_manager.py

The "max_transforms" property used to be read when debug-printing a Pass object, but wasn't guaranteed to be initialized on all codepaths (especially not in unit tests). Ensure this via constructor, to prevent misleading error messages.

passes: Ensure max_transforms is initialized

---

cvise-cli.py

This is to support a different file layout in downstream projects, placing the `cvise` Python package in a top-level folder.

Allow the search for cvise script in the top-level directory.

---

cvise/passes/clanghints.py
cvise/passes/hint_based.py
cvise/passes/line_markers.py
cvise/passes/lines.py
cvise/tests/test_hint.py
cvise/tests/test_hint_based.py
cvise/utils/hint.py

Refactor the code to pass hints as a bundle object instead of the naked list.
This is preparation for introducing additional items of data stored next to hints - e.g., "vocabulary" of strings shared between hints.

hints: Add bundle class

---

cvise-cli.py

Reverts marxin/cvise#215 - the change breaks the tests.

Revert "Allow the search for cvise script in the top-level directory."

---

clang_delta/HintsBuilder.cpp
clang_delta/HintsBuilder.h
clang_delta/Transformation.cpp
cvise/passes/clanghints.py
cvise/tests/test_clanghints.py
cvise/tests/test_hint.py
cvise/utils/hint.py
tests/test_cvise.py

Implement support for hints that replace text with the new value. In order to have a compact representation, use a "vocabulary" - a string table that hints can refer to; the vocabulary can also be used for other features in the future.
This is preparation for porting heuristics that do text replacements to the hint-based framework.

hints: Support text replacement patches

---

cvise/passes/clanghints.py
cvise/passes/hint_based.py
cvise/tests/test_hint_based.py
cvise/utils/hint.py
pyproject.toml

This will be used for passes that return several groups of reduction opportunities, with different success rate and whose contiguous ranges are better to attempt separately (e.g., the "balanced" pass replacing round bracket pairs vs. square bracket pairs).

hints: Introduce hint type; run independent binsrch per type

---

.github/workflows/build-llvm-nightly.yml
.github/workflows/build.yml

Even when multiple commits land in a quick succession to the master branch, we still want to test them all; cancelling concurrent jobs was resulting in spurious "failures" displayed on Github.

CI: Don't cancel jobs for the master branch

---

cvise/pass_groups/all.json
cvise/tests/test_lines.py
delta/topformflat.l
tests/test_cvise.py

Enhance the topformflat Flex grammar rules to only generate nontrivial hints, i.e. those consisting of non-whitespaces. Empirically, this reduces the number of hints by around 20%; and extra whitespaces are easy to remove at the end of reduction.
As a byproduct of this change, we were able to stricten some unit tests - now the distracting whitespace-only removals don't happen.
Another functional change: only treat "#" characters as a start of a macro if it's the first character or there are only whitespaces before it; this should be a pure improvement too.

lines: Don't generate hints for whitespace-only blocks

---

delta/topformflat.l

"%option fast" makes the topformflat scanner faster at the cost of binary size. Empirical improvement is ~50%: improving the throughput from 200 MiB/sec to 300 MiB/sec (numbers taken on my machine). The topformflat binary size increase is O(KBs), which is negligible.

lines: Configure Flex to use fast scanning mode

---

cvise/CMakeLists.txt
cvise/passes/blank.py
cvise/tests/test_blank.py

Similar to other commits in the series, porting a pass to the hint-based architecture allows for better parallelization in the future.
I've ported the heuristic as-is - with both '^\s*$' and '^#' regexps, even though I'm not sure about the benefit of the second pattern. The new implementation gives them different "t", so that they're attempted independently, like the old implementation was doing.

hints: Migrate blank pass

---

cvise/passes/hint_based.py

Dump the hint types, number and the binary search state when formatting for logs (used under --debug or when specific exceptions occur).

hints: Debug logging of the state object

---

cvise/passes/abstract.py
cvise/passes/balanced.py
cvise/passes/blank.py
cvise/passes/clang.py
cvise/passes/clangbinarysearch.py
cvise/passes/clanghints.py
cvise/passes/clex.py
cvise/passes/comments.py
cvise/passes/gcdabinary.py
cvise/passes/hint_based.py
cvise/passes/ifs.py
cvise/passes/includeincludes.py
cvise/passes/includes.py
cvise/passes/indent.py
cvise/passes/ints.py
cvise/passes/peep.py
cvise/passes/special.py
cvise/passes/ternary.py
cvise/passes/unifdef.py
cvise/tests/test_test_manager.py

Let all advance_on_success() methods receive arbitrary key-value arguments without needlessly mentioning them explicitly.
This is analogous to #180, and is a preparation for passing timeouts to passes which need them.

Refactor arg passing for Pass.advance_on_success()

---

cvise/utils/testing.py

Introduce an object to store all pass-related information together.
This consolidates a few properties of the TestManager class, and allows us to introduce more fields without error-prone boilerplate.

Refactor pass runtime state in test manager

---

cvise/passes/clangbinarysearch.py
cvise/passes/clanghints.py
cvise/tests/test_clanghints.py
cvise/utils/testing.py

The old ClangBinarySearchPass class used to hardcode the 10-second timeout, which was insufficient for big inputs and led to a significant slowdown of the reduction as this heuristic didn't work at all. The new ClangHintsPass didn't have the timeout logic at all, which would result in hanging C-Vise if building Clang AST hangs.
Fix both places to use the --timeout command-line parameter value.

clang_delta: Use real timeout for old&new passes

---

cvise/cvise.py
cvise/tests/test_test_manager.py
cvise/utils/testing.py

Receive an explicit flag telling whether we're executing an "interleaving" set of passes from the config. Previously, the code was checking "is there more than one pass", which isn't exactly the same.
This will start making difference once we introduce more interleaving-specific features, namely the folding (merging of concurrently discovered reductions).

test_manager: Know whether pass category is interleaving

---

cvise/pass_groups/all.json
cvise/utils/testing.py
tests/test_cvise.py

Pick an arbitrary transformation among multiple ones that succeeded, instead of preferring the one that's scheduled earlier.
The main goal is the upcoming support of folding (i.e., merging multiple concurrently discovered successful transformations), where preferring a bigger, rather than an earlier, reduction will be crucial. Other benefits: slow/timing-out jobs won't "stand in the way" of proceeding with a successful transformation; implementation of TestManager doesn't need to repeat the job status checking logic in two different places.
The downside of this change is that it makes reductions non-deterministic. Additionally, there's a temporary problem that C-Vise might skip some opportunities in the "cleanup" passes - for example, to avoid the flakiness in test_cvise.py we had to …

test_manager: Proceed on any success, not necessarily the first

---

cvise-cli.py
cvise/passes/blank.py
cvise/passes/comments.py
cvise/passes/hint_based.py
cvise/passes/line_markers.py
cvise/passes/lines.py
cvise/tests/test_blank.py
cvise/tests/test_clanghints.py
cvise/tests/test_comments.py
cvise/tests/test_hint.py
cvise/tests/test_hint_based.py
cvise/tests/test_line_markers.py
cvise/tests/test_lines.py
cvise/tests/testabstract.py
cvise/utils/hint.py
cvise/utils/misc.py
cvise/utils/testing.py
delta/topformflat.l
tests/test_cvise.py

Accept test cases that aren't valid UTF-8. While unusual in modern programming, non-UTF-8 files do still occur (e.g., in tests of text parsing libraries).
This commit adds support of non-UTF-8 reductions into the following passes: blank, comments, clanghints, line_markers, lines. Other passes will be silently skipped on Unicode errors. Also make the "--print-diff" logic support non-UTF-8 files too.
This should address most of #59.

Support non UTF-8 inputs

---

cvise/CMakeLists.txt
cvise/pass_groups/no-interleaving.json
tests/test_cvise.py

Add an interleaving category into the all.json config - this means C-Vise will use the new logic with running different passes concurrently by default. In case of problems or performance issues with it, the user can fall back to "--pass-group no-interleaving" (this config is the old all.json before this commit).
For now, we only use the "interleaving_first" category, which means going through all reduction candidates once - without looping until all passes are exhausted. We'll reevaluate this later once more performance improvements get into the "interleaving" code path and more passes are migrated to be compatible with it.

interleaving: Enable by default

---

cvise/tests/test_test_manager.py
cvise/utils/testing.py

Fix the mistake that resulted in first scheduling all jobs for the first pass only, then all jobs for the second pass only, etc. - instead of a permutation-like order (one job per pass).

interleaving: Fix round-robin order

---

cvise-cli.py

Print the "--- \<testcase\> ---" line into the same output as all other precending&following logs - either stderr or the log file. It seems like it was an oversight to send only this log to stdout.
(We touched this code in #244, but the discrepancy was in the code before that change.)

cli: Send file name log to intended output

---

cvise/passes/abstract.py
cvise/utils/testing.py

When executing an interestingness test, make it use a custom temp dir, located inside the job's temporary folder, instead of the default location (like /tmp/ on a typical POSIX system). This allows C-Vise to clean up all temporary files it might've created without cluttering the default location.
Examples of problematic cases which this commit attempts to solve:
* The interestingness script launches GCC which creates a temporary `.s` file; meanwhile it's normally removed on GCC process exit, it doesn't happen when C-Vise kills cancelled jobs via SIGKILL.
* The interestingness script launches Clang without `-fno-crash-diagnostics`; once Clang crashes, it writes a the crash reproducer file to the temporary directory.
This fixes #260 (hopefully).

Override child processes' temp dir

---

cvise/utils/testing.py

This was documented as a measure to increase the responsiveness, but according to my measurements it only slows down C-Vise: e.g., simple reductions finish in ~113 sec instead of ~86 sec (30% slowdown). Pebble seems to use proper synchronization primitives that don't require tweaking timeouts for quick processing.
Presumably the slowdown is caused by the increased thread congestion, which with Python's Global Interpreter Lock decreases the main process' throughput.

test_manager: Don't override Pebble sleep unit

---

cvise/utils/testing.py

Each time we commit to a reduction, schedule all passes' advance_on_success() methods to be executed in workers in parallel, as opposed to running them sequentially.
This significantly improves the performance of the "interleaving" mode, since we previously were spending 20-40% of wall clock time in those single-job advance_on_success() calls for heavy inputs.
Example measurements on a 64-core machine for the "gcc-94937" reproducer:
* before: reduced 54.4% after 5 min, 78.7% after 10 min.
* after: reduced 58.1% after 5 min, 85.2% after 10 min.

interleaving: Concurrently execute advance_on_success

---

CMakeLists.txt
tree-sitter/CMakeLists.txt

Add a handwritten CMake source file.
We don't use upstream's existing build scripts (Tree-sitter uses Makefile), since it's nontrivial to integrate it seamlessly into the CMake project, and also the build story for our purposes (a static library) is quite simple.

tree-sitter: Build rule

---

CMakeLists.txt
clang_delta/CMakeLists.txt
clex/CMakeLists.txt
delta/CMakeLists.txt
tree-sitter/CMakeLists.txt

Trigger building the Tree-sitter C++ grammar.
We simply reuse the CMake source file from the upstream. The only tweak is disabling dynamic library creation, which the upstream CMake sets to "on" by default.
On the C-Vise side, we stop applying "-pedantic" unilaterally, since it doesn't work for Tree-sitter subdirectories.

tree-sitter-cpp: Build rule

---

cvise/utils/testing.py

After a pass finished enumerating all of its state, reinitialize it again
if we made reductions via other passes (in the interleaving mode).
This significantly improves the reduction pace in its mid-term stage,
when some passes already went through all of the candidates once
but there's still a couple of passes that continue making successful
reductions. For example, `LinesPass` is likely to finish before `rm-tok`
(as there's more tokens that curly brace pairs), however removing
some token can make some curly-brace-surrounded block
removable too - this is where the reinitialization of `LinesPass`
would help discovering this sooner, within the same batch of jobs
in run_passes().
We just need to make sure we don't do reinits too often, since for
some passes they're mostly useless (think of …

interleaving: Reinit finished passes once in a while

---

cvise/passes/clangbinarysearch.py

Fix the regression introduced in #265:
```
File "\cvise/utils/testing.py", line 151, in run
(result, self.state) = self.transform(
~~~~~~~~~~~~~~^
str(self.test_case_path), self.state, ProcessEventNotifier(self.pid_queue)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "\cvise/passes/clangbinarysearch.py", line 117, in transform
self.parse_stderr(state, stderr)
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File "\cvise/passes/clangbinarysearch.py", line 90, in parse_stderr
for line in stderr.split('\n'):
~~~~~~~~~~~~^^^^^^
TypeError: a bytes-like object is required, not 'str'
```
This pass has only minor importance currently, being gradually superseded by ClangHints, still as long as it's still present we should fix the error.

clangbinarysearch: Fix TypeError due to byte-str mixup

---

CMakeLists.txt

Don't execute by default all CMake rules in tree-sitter and tree-sitter-cpp - instead, only those rules will be executed that are depended by something else (currently only treesitter_delta).
This fixes the problem that installing C-Vise would result in installing tree-sitter-cpp public .h/.so files into system-wide locations. This fixes #284.

tree-sitter, tree-sitter-cpp: Don't install into system location

---

cvise/passes/abstract.py
cvise/passes/hint_based.py
cvise/tests/test_folding.py
cvise/utils/folding.py
cvise/utils/testing.py

Change a few "state" classes to let them be used for comparison and for hashing containers.
This refactoring should have no functional effect, but it's a prerequisite for a follow-up change where state comparisons will be necessary.

Make State objects immutable and hashable

---

cvise/passes/lines.py
cvise/tests/test_lines.py
cvise/tests/testabstract.py

Migrate the Lines pass to support the multi-file (i.e., directory instead of a single file) inputs.

multifile: Add support to Lines pass

---

tests/test_cvise.py

Slightly improve test_cvise.py to not create temporary files in its own location, and use temporary directories instead.
This makes the tests more reliable and compatible with build systems like Bazel that don't allow modifying input files. Also it simplifies the implementation of multi-file (directory) reduction tests, where the cleanup would be more annoying to write.

test_cvise: Use temp dir instead of in-tree files

---

CMakeLists.txt

Ignore the externally specified BUILD_SHARED_LIBS value when building tree-sitter and tree-sitter-cpp, and link them statically always. This is another fix for #284.

tree-sitter: Always link statically

---

cvise/passes/treesitter.py
cvise/tests/test_treesitter.py
cvise/utils/process.py
treesitter_delta/CMakeLists.txt
treesitter_delta/EraseNamespace.cpp
treesitter_delta/EraseNamespace.h
treesitter_delta/Main.cpp
treesitter_delta/RemoveFunction.cpp
treesitter_delta/RemoveFunction.h
treesitter_delta/ReplaceFunctionDefWithDecl.cpp
treesitter_delta/ReplaceFunctionDefWithDecl.h
treesitter_delta/Transformation.h
treesitter_delta/TransformationFactory.cpp
treesitter_delta/TransformationFactory.h

Migrate all Tree-sitter based heuristics (replace-function-def-with-decl, erase-namespace, remove-function) to support multi-file inputs, i.e. test cases that are directories.
Note: "remove-function" is the first truly cross-file heuristic, as it's attempting to remove all function defs/decls sharing the same name from all files.

multifile: Add support to Tree-sitter pass

---

tests/test_cvise.py

Hardcode a specific '-n' value in the test, so that it doesn't deviate significantly depending on how beefy the machine is. Also graceful worker termination would take more time than the hardcoded timeout for a very big number of workers.

test_cvise: Use specific worker count

---

tests/test_cvise.py

Reverts marxin/cvise#317 due to test failures - this commit uncovered a couple of problems that need to be addressed first.

Revert "test_cvise: Use specific worker count"

---

tests/test_cvise.py

Reverts marxin/cvise#320, relanding marxin/cvise#317. The issues causing test flakiness should be resolved now.

Reland "test_cvise: Use specific worker count"

---

.github/workflows/build-llvm-nightly.yml
.github/workflows/build.yml
INSTALL.md

Use the pytest-xdist plugin to run tests concurrently to each other,
to shorten the wait time.
We use the "number_of_processing_units + 1" formula, to improve
resource utilization when tests are bound by i/o or other waits.

tests: Run pytest tests in parallel

---

CMakeLists.txt
conftest.py

Some unit tests run child processes, and before this commit they used the default multiprocessing mode ("fork" on *nix currently).
Change all tests to use "forkserver", to be consistent with the mode actually used by the C-Vise when it's run via the CLI tool.

multiprocessing: Use forkserver in all tests

---

cvise/tests/test_test_manager.py

Before asserting the state at the end of the test, make sure to shut down the manager to let multi-threaded logic complete.

Fix flaky test_test_manager: wait for mgr shutdown

---

cvise/cvise.py
cvise/tests/test_test_manager.py
cvise/utils/process.py
cvise/utils/sigmonitor.py
cvise/utils/testing.py

Don't allow signals to interrupt run_process() in a way that neither FINISHED nor ORPHANED are returned.
Refactor the sigmonitor code so that various modes (os._exit, raise, remember-but-raise-on-demand-only) are easier to control and to reduce the runtime overhead if we add it into hotpaths.

subprocesses: Make PID queue robuster to signals

---

cvise/passes/blank.py
cvise/passes/clangmodulemap.py
cvise/passes/comments.py
cvise/passes/hint_based.py
cvise/passes/treesitter.py
cvise/tests/test_blank.py
cvise/tests/test_clanghints.py
cvise/tests/test_clangmodulemap.py
cvise/tests/test_clexhints.py
cvise/tests/test_comments.py
cvise/tests/test_hint.py
cvise/tests/test_hint_based.py
cvise/tests/test_line_markers.py
cvise/tests/test_lines.py
cvise/tests/test_treesitter.py
cvise/tests/testabstract.py

Each pass now explicitly declares types of the hints it produces.
This will be used to implement pass dependencies - some passes consuming the information produced by others.

hints: Passes declare output hint types

---

cvise/utils/error.py
cvise/utils/testing.py
tests/test_cvise.py

Check at the very start whether the user-specified interestingness script lies inside any of the test cases - this is unsupported and likely to bring troubles (as a randomly-modified shell script won't perform any useful check, and may even be dangerous to run).

multifile: Forbid interestingness script inside test case

---

cvise/tests/test_fileutil.py
cvise/utils/fileutil.py
tests/test_cvise.py

This removes the need in specifying "--no-cache" when reducing directory (multi-file) test cases.
Implementation-wise, the only missing piece was computing a hash of a directory - all other primitives used by the cache already support dirs.

multifile: Support caching

---

cvise/passes/makefile.py

Suppress removal of Makefiles in the RmUnusedFilesPass, because in a typical use case the makefile would be used by the interestingness test to compile the source.
An ideal solution would be to detect whether a makefile is actually used during the interestingness test's invocation, but currently C-Vise cannot make any insights into the interestingness tests. In the future an strace-like solution might be considered.

multifile: Assume all Makefiles to be used

---

clex/clex.l
clex/defs.h
clex/driver.c
clex/strlex.l
cvise/tests/test_clexhints.py

Fix the ClexHintsPass returning no hints when a directory (multi-file) test case has files with unfinished C-style comments.
Implementation-wise, there were two issues: first, Flex doesn't report EOF from input() when it was the last file and yywrap() куегктув тщтяукщ; repeatedly calling input() was causing a segfault. Second, we should stop the loop that "eats" comments when we cross input file boundary.

multifile: Fix Clex rm-toks crash on unended comments

---

clang_include_graph/Main.cpp
cvise/passes/clangincludegraph.py
cvise/tests/test_clangincludegraph.py

Support Clang C/C++ header modules when extracting the include graph in ClangIncludeGraphPass.
Implementation-wise, we have to manipulate the command line because "-fmodule-file=..." arguments would refer to non-existing PCM files, so these and "-fmodule-map-file=..." arguments that depend on them have to be deleted.
On the other hand, "-fmodules" has to be kept, otherwise we won't be able to easily run Clang's preprocessor on a modulemap file. Also "-fmodule-map-file-home-is-cwd", if present, has to be kept - otherwise Clang won't find the headers mentioned in the modulemap.

ClangIncludeGraph: Support Clang Header Modules

---

cvise/passes/makefile.py
cvise/tests/test_makefile.py
cvise/utils/makefileparser.py

Implement a new heuristic that removes a makefile target together with all references to it (in prerequisites and command lines).
Also improve the "remove-arguments-across-all-commands" heuristic in the same pass to not leave extraneous spaces around the deleted arguments.

multifile: MakefilePass removes targets

---

cvise/utils/fileutil.py
cvise/utils/testing.py

Logs for directory (multi-file) test cases will look like:
`00:30:26 INFO (58.7%, 9998801 bytes, 149447 lines, 2481 files in 675 dirs, ...)`

multifile: Print file&dir count in logs

---

tests/test_cvise.py

Increase timeouts in test_kill, since it's flaky on CI bots (presumably when the machine is overloaded).

signals: Increase timeout in tests

---

cvise-cli.py
cvise/passes/clangincludegraph.py
cvise/passes/clangmodulemap.py
cvise/passes/clexhints.py
cvise/passes/hint_based.py
cvise/passes/lines.py
cvise/passes/makefile.py
cvise/passes/treesitter.py
cvise/utils/hint.py

Make sure hints are sorted lexicographically: by file, type, 'l'/'r' indices within the same file, etc.
This makes sure passes enumerate reduction possibilities in a stable and well-defined order.

hints: Sort hints in all passes

---

cvise-cli.py
cvise/passes/clangincludegraph.py
cvise/passes/clangmodulemap.py
cvise/passes/clexhints.py
cvise/passes/hint_based.py
cvise/passes/lines.py
cvise/passes/makefile.py
cvise/passes/treesitter.py
cvise/utils/hint.py

Reverts marxin/cvise#378 due to errors observed in manual testing:
`'<' not supported between instances of 'int' and 'NoneType'`

Revert "hints: Sort hints in all passes"

---

tests/test_cvise.py

The semi-integration test of reducing blocksort-part.c can sometimes end up with yet another result: "#undef nextHi". This was causing occasional flakiness of the test.

tests: Add another possible output into test_cvise

---

cvise/passes/abstract.py
cvise/passes/clanghints.py
cvise/passes/hint_based.py
cvise/tests/test_balanced.py
cvise/tests/test_comments.py
cvise/tests/test_fileutil.py
cvise/tests/test_lines.py
cvise/tests/testabstract.py
cvise/utils/fileutil.py
cvise/utils/testing.py

Only allow regular characters (a-zA-Z0-9_.-) in file names that C-Vise creates for internal needs.
First, this fixes an annoying problem that the interestingness script could be executed in a folder with spaces in the names - and it's pretty hard for the user of C-Vise to discover if their Shell script doesn't support this. Second, it makes sure we don't use hint types - which can be arbitrary strings - to form malformed file names.
As a bonus, this commit simplifies implementing a better folding mechanism in the future, with reusing successful discoveries from a previous batch of jobs that didn't make it into the best folding attempt.

hints, test_manager: Sanitize and randomize file names

---

cvise-cli.py
cvise/passes/clangincludegraph.py
cvise/passes/clangmodulemap.py
cvise/passes/clexhints.py
cvise/passes/hint_based.py
cvise/passes/lines.py
cvise/passes/makefile.py
cvise/passes/treesitter.py
cvise/tests/test_balanced.py
cvise/tests/test_hint.py
cvise/utils/hint.py

Compared to the original patch (#378), we now properly support comparing Nones with non-Nones in fields. Original patch description:
Make sure hints are sorted lexicographically: by file, type, 'l'/'r' indices within the same file, etc.
This makes sure passes enumerate reduction possibilities in a stable and well-defined order.

hints: Reland "Sort hints in all passes"
